spring:
  application:
    name: Cart
  jackson:
    default-property-inclusion: non_null
  cloud:
    bus:  
      enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}

eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

server:
  port: 8030

management:
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh
