spring:
  application:
    name: Cart
  jackson:
    default-property-inclusion: non_null

server:
  port: 8030

management:
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh
