spring:
  application:
    name: Cart
  jackson:
    default-property-inclusion: non_null
  cloud:
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: false
    bus:  
      enabled: true
    function:
      definition: clearItems
    stream:
      bindings:
        #xoa items
        clearItems-in-0:
          destination: clear-items
          content-type: application/json
          group: clear-items-group

  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}

# eureka:
#   instance:
#     preferIpAddress: true
#   client:
#     register-with-eureka: true
#     fetch-registry: true
#     service-url:
#       defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

server:
  port: 8030

management:
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh
