server:
  port: 8000
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        corsConfigurations:
          '[/**]': # CORS cho tất cả các route
            allowedOrigins: "http://localhost:3000" # Địa chỉ frontend React
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true


      routes:
        - id: user-service
          uri: lb://USER
          predicates:
            - Path=/user/**,/USER/**
          filters:
            - StripPrefix=1
            - name: AddSubHeader
          order: -1

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/myrealm

eureka:
  client:
    register-with-eureka: true   # Cho phép đăng ký với Eureka
    fetch-registry: true         # Lấy danh sách các service khác
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info