server:
  port: 8000
spring:
  application:
    name: gateway
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
  cloud:
    # kubernetes:
    #   discovery:
    #     enabled: true
    #     all-namespaces: false
    bus:  
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        corsConfigurations:
          '[/**]': # CORS cho tất cả các route
            allowedOrigins: ${FE_URL:http://localhost:3000} # Địa chỉ frontend React
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            
      routes:
        - id: user-service
          uri: lb://USER
          predicates:
            - Path=/user/**,/USER/**
          filters:
            - StripPrefix=1
            - name: AddSubHeader
          order: -1
        - id: cart-service
          uri: lb://CART
          predicates:
            - Path=/cart/carts,/CART/carts,/cart/carts/create,/CART/carts/create
          filters:
            - StripPrefix=1
            - name: AddSubHeader
          order: -1

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${RESOURCESERVER_JWT_ISSUSERURI:http://localhost:8080/realms/myrealm}
          
eureka:
  client:
    register-with-eureka: true   # Cho phép đăng ký với Eureka
    fetch-registry: true         # Lấy danh sách các service khác
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info
