server:
  port: 8040

spring:
  application:
    name: inventory
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}

  jackson:
    default-property-inclusion: non_null

  cloud:
    bus:  
      enabled: true
    # kubernetes:
    #   discovery:
    #     enabled: true
    #     all-namespaces: false
    function:
      definition: processCreateInventory;processDeleteInventory;processReservedInventory;processReleaseInventory
    stream:
      bindings:
        processCreateInventory-in-0:
          destination: create-inventory
          group: inventory-group
          content-type: application/json
        processFailedInventory-out-0:
          destination: fail-inventory
          content-type: application/json

        processDeleteInventory-in-0:
          destination: delete-inventory
          group: inventory-delete-group
          content-type: application/json
        processDeletedInventory-out-0:
          destination: deleted-inventory
          content-type: application/json

        #order
        processReservedInventory-in-0:
          destination: reserve-inventory
          group: inventory-reserved-group
          content-type: application/json
        processFailedOrder-out-0:
          destination: fail-order
          content-type: application/json

        #order
        processReleaseInventory-in-0:
          destination: release-inventory
          group: inventory-release-group
          content-type: application/json

        #order clear cart
        clearItems-out-0:
          destination: clear-items
          content-type: application/json
        

      kafka:
        binder:
          brokers: ${KAFKA_BROKERS:localhost:9092}
          auto-create-topics: true

eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh, busrefresh
