server:
  port: 9000

spring:
  application:
    name: order
  jackson:
    default-property-inclusion: non_null
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}

  cloud:
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: false
    bus:  
      enabled: true
    function:
      definition: processReservedInventoryFailEvent;processCanceledInventoryFailEvent
    stream:
      bindings:
        #dat hang
        sendReservedInventory-out-0:
          destination: reserve-inventory
          content-type: application/json
        processReservedInventoryFailEvent-in-0:
          destination: fail-order
          content-type: application/json
          group: fail-reserve-order-group

        #huy hang
        sendCancelInventory-out-0:
          destination: release-inventory
          content-type: application/json

      kafka:
        binder:
          brokers: ${KAFKA_BROKERS:localhost:9092}
          auto-create-topics: true
          
feign:
  client:
    config:
      product-service:
        connect-timeout: 2000
        read-timeout: 3000

# eureka:
#   instance:
#     preferIpAddress: true
#   client:
#     register-with-eureka: true
#     fetch-registry: true
#     service-url:
#       defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh, busrefresh
