server:
  port: 9000

spring:
  application:
    name: order

  cloud:
    function:
      definition: processReservedInventoryFailEvent;processCanceledInventoryFailEvent
    stream:
      bindings:
        #dat hang
        sendReservedInventory-out-0:
          destination: reserve-inventory
          content-type: application/json
        processReservedInventoryFailEvent-in-0:
          destination: fail-order
          content-type: application/json
          group: fail-reserve-order-group

        #huy hang
        sendCancelInventory-out-0:
          destination: release-inventory
          content-type: application/json

      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
          
feign:
  client:
    config:
      product-service:
        connect-timeout: 2000
        read-timeout: 3000

eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh, busrefresh
