server:
  port: 8070

spring:
  application:
    name: user
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
  cloud:
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: false
    bus:  
      enabled: true
  jackson:
    default-property-inclusion: non_null

api:
  prefix: api/v1

# eureka:
#   instance:
#     preferIpAddress: true
#   client:
#     register-with-eureka: true
#     fetch-registry: true
#     service-url:
#       defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh, busrefresh
